; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "iPropertiesController"
#define MyAppVersion "1.0"
#define MyAppPublisher "the-war-horse, alexf."
#define MyAppURL "https://graitectechnical.slack.com/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{57C51ACA-1674-477C-BAA5-67C59E1EF798}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\ProgramData\Autodesk\ApplicationPlugins\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=C:\temp\iPropertiesController_Installer
OutputBaseFilename=iPropertiesController_setup
SetupIconFile=C:\Users\Alex.Fielder\Source\Repos\iPropertiesController\iPropertiesController\Resources\addin.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\Users\Alex.Fielder\Source\Repos\iPropertiesController\iPropertiesController\bin\Release\autodesk.inventor.interop.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Alex.Fielder\Source\Repos\iPropertiesController\iPropertiesController\bin\Release\Autodesk.iPropertiesController.Inventor.addin"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Alex.Fielder\Source\Repos\iPropertiesController\iPropertiesController\bin\Release\iPropertiesController.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Alex.Fielder\Source\Repos\iPropertiesController\iPropertiesController\bin\Release\log4net.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Alex.Fielder\Source\Repos\iPropertiesController\iPropertiesController\bin\Release\log4net.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Alex.Fielder\Source\Repos\iPropertiesController\iPropertiesController\bin\Release\Log4NetFileHelper.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Alex.Fielder\Source\Repos\iPropertiesController\iPropertiesController\bin\Release\Log4NetFileHelper.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Alex.Fielder\Source\Repos\iPropertiesController\iPropertiesController\bin\Release\Log4NetFileHelper.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Alex.Fielder\Source\Repos\iPropertiesController\iPropertiesController\bin\Release\stdole.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

