; Installer for the iPropertiesController Inventor add-in (.NET 8, Inventor 2025 and later).
; Compiled automatically by the Release build's post-build step, or by hand with:
;   "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer.iss
; Build Release first: everything is taken from the Release build output.

#define MyAppName "iPropertiesController"
#define MyAppPublisher "the-war-horse, alexf."
#define MyAppURL "https://github.com/AlexFielder/MyFirstInventorAddin"
#define BinDir AddBackslash(SourcePath) + "..\bin\Release\net8.0-windows"
; The version comes from the built DLL (generated by AssemblyInfo.tt on every build).
#define MyAppVersion GetFileVersionString(BinDir + "\iPropertiesController.dll")
; The licence server compares only the first three version parts (the fourth increments on every
; build); the setup file is named with those, e.g. iPropertiesController-Setup-2026.0.14.exe, which
; is also the asset name expected on the GitHub release tagged v2026.0.14.
#define VerMajor
#define VerMinor
#define VerRelease
#define VerBuild
#expr GetVersionComponents(BinDir + "\iPropertiesController.dll", VerMajor, VerMinor, VerRelease, VerBuild)
#define ReleaseVersion Str(VerMajor) + "." + Str(VerMinor) + "." + Str(VerRelease)


; Code signing, as for the other AF Automations installers: only when the certificate password
; is available (AFA_PFX_PASSWORD, never committed) and a sign tool named "signtool" is
; registered in the Inno Setup IDE (Tools > Configure Sign Tools).
#define SignedPw GetEnv("AFA_PFX_PASSWORD")

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
AppId={{57C51ACA-1674-477C-BAA5-67C59E1EF798}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
VersionInfoVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; Inventor loads .addin files for all users and all versions from this folder. The Debug build
; deploys to the same place.
DefaultDirName={commonappdata}\Autodesk\Inventor Addins\{#MyAppName}
DisableDirPage=yes
; Earlier installers used ApplicationPlugins\iPropertiesController; don't reuse that location.
UsePreviousAppDir=no
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=Output
OutputBaseFilename={#MyAppName}-Setup-{#ReleaseVersion}
SetupIconFile=..\Resources\addin.ico
Compression=lzma2
SolidCompression=yes
PrivilegesRequired=admin
ChangesEnvironment=yes
#if SignedPw != ""
SignTool=signtool /d $q{#MyAppName}$q /du $q{#MyAppURL}$q /fd sha256 /f $qC:\AFAutomations\tools\AFAutomations.pfx$q /p $q{#SignedPw}$q /t $qhttp://timestamp.digicert.com$q /v $f
SignedUninstaller=yes
SignToolRunMinimized=yes
#endif

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Dirs]
; Licence files and logs. Users need write access: the licence is renewed and the log written as the
; signed-in user. Kept on uninstall so a reinstall stays activated.
Name: "{commonappdata}\AFAutomations\{#MyAppName}"; Permissions: users-modify; Flags: uninsneveruninstall

[InstallDelete]
; The old installer's location, which Inventor does not load .addin files from.
Type: filesandordirs; Name: "{commonappdata}\Autodesk\ApplicationPlugins\{#MyAppName}"
; Files from earlier versions: log4net (replaced by Serilog) and the old app.config.
Type: files; Name: "{app}\log4net.*"
Type: files; Name: "{app}\Log4Net.config"
Type: files; Name: "{app}\Log4NetFileHelper.*"
Type: files; Name: "{app}\iPropertiesController.dll.config"

[Files]
Source: "{#BinDir}\Autodesk.iPropertiesController.Inventor.addin"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BinDir}\iPropertiesController.dll"; DestDir: "{app}"; Flags: ignoreversion
; deps.json lets .NET resolve the add-in's NuGet dependencies from this folder.
Source: "{#BinDir}\iPropertiesController.deps.json"; DestDir: "{app}"; Flags: ignoreversion
; Every dependency the build copies (Serilog and sinks, System.* packages, the Inventor interop
; and stdole) - the same set as the Debug deployment. The add-in itself is listed above.
Source: "{#BinDir}\*.dll"; Excludes: "iPropertiesController.dll"; DestDir: "{app}"; Flags: ignoreversion
; Platform-specific assemblies that deps.json points at; the folder layout must be kept.
Source: "{#BinDir}\runtimes\*"; DestDir: "{app}\runtimes"; Flags: ignoreversion recursesubdirs createallsubdirs

[Registry]
; Earlier installers wrote the Seq key machine-wide. It now comes from the licence, and a leftover
; value would override it, so remove it.
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: none; ValueName: "AFA_IPROPERTIES_SEQ_APIKEY"; Flags: deletevalue

[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
