' <auto-generated>
'     Generated from AssemblyInfo.tt by the PreBuild target in iPropertiesController.vbproj.
'     Edit the template, not this file.
' </auto-generated>
Imports System.Reflection
Imports System.Runtime.InteropServices
Imports System.Runtime.Versioning

<Assembly: AssemblyTitle("iPropertiesController")>
<Assembly: AssemblyDescription("iPropertiesController for Autodesk Inventor")>
<Assembly: AssemblyCompany("the-war-horse, alexf.")>
<Assembly: AssemblyProduct("Autodesk Inventor iPropertiesController")>
<Assembly: AssemblyCopyright("Copyright © 2017 the-war-horse, alexf.")>
<Assembly: AssemblyTrademark("")>

'The following GUID is for the ID of the typelib if this project is exposed to COM
<Assembly: Guid("be85cfee-b3c2-4c19-a2c9-15c5d126e2d4")>

' Inventor add-ins only run on Windows; this also stops the platform-compatibility (CA1416)
' warnings that the SDK's generated assembly info would otherwise suppress.
<Assembly: SupportedOSPlatform("windows")>

<Assembly: AssemblyVersion("2026.0.0.0")>
<Assembly: AssemblyFileVersion("2026.0.0.0")>
