<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <StartupObject>
    </StartupObject>
    <MyType>Windows</MyType>
    <PublishUrl>http://localhost/InventorAddIn/</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Web</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>true</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
	<UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	  <ProjectName Condition=" '$(ProjectName)' == '' ">iPropertiesController</ProjectName>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
    <PropertyGroup>
    <OptionExplicit>Off</OptionExplicit>
  </PropertyGroup>
  <PropertyGroup>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\CHECKIN.png" />
    <None Remove="Resources\CHECKOUT.png" />
    <None Remove="Resources\green_button_tick.png" />
    <None Remove="Resources\paperclip1.jpg" />
    <None Remove="Resources\white_button.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Autodesk.Inventor.Interop">
      <HintPath>..\..\..\..\Program Files\Autodesk\Inventor 2025\Bin\Public Assemblies\Autodesk.Inventor.Interop.dll</HintPath>
      <Private>True</Private>
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </Reference>
    <Reference Include="stdole">
      <HintPath>..\..\..\..\Program Files\Autodesk\Inventor 2025\Bin\stdole.dll</HintPath>
    </Reference>
    <Reference Update="System">
      <Name>System</Name>
    </Reference>
	  <Reference Update="System.Windows.Forms">
		  <Name>System.Windows.Forms</Name>
	  </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="iPropertiesForm.Designer.vb">
      <DependentUpon>iPropertiesForm.vb</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Autodesk.iPropertiesController.Inventor.addin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Windows.Installer.3.1">
      <Visible>False</Visible>
      <ProductName>Windows Installer 3.1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\white_button.png" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\paperclip1.jpg" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\addin.ico" />
    <Content Include="Resources\CHECKIN.png" />
    <Content Include="Resources\CHECKOUT.png" />
    <Content Include="Resources\green_button_tick.png" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\paperclip.jpg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.3.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="System.Windows" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Log4NetFileHelper\Log4NetFileHelper.vbproj" />
  </ItemGroup>
	<ItemGroup>
		<Service Include="{e691af34-cb32-4296-8cca-5d1027a27c72}" />
	</ItemGroup>
  <PropertyGroup>
    <PostBuildEvent>echo Configuration: $(Configuration)
	echo SolutionDir: $(SolutionDir)
echo OutDir: $(OutDir)
echo ProjectDir: $(ProjectDir)
echo ProjectName: $(ProjectName)
echo TargetDir: $(TargetDir)
if "$(Configuration)"=="Debug" (
XCopy "$(TargetDir)*.*" "C:\ProgramData\Autodesk\Inventor Addins\$(ProjectName)\*.*" /Y /R
if not exist "C:\Logs" mkdir "C:\Logs"
)
if "$(Configuration)"=="Release" (
cd "$(ProjectDir)\Installer"
"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer.iss"
)</PostBuildEvent>
    <AssemblyTitle>iPropertiesController</AssemblyTitle>
    <Description>iPropertiesController for Autodesk Inventor</Description>
    <Company>the-war-horse, alexf.</Company>
    <Product>Autodesk Inventor iPropertiesController</Product>
    <Copyright>Copyright %3f2017 the-war-horse, alexf.</Copyright>
    <AssemblyVersion>16.0.0.%2a</AssemblyVersion>
    <ImportedNamespaces>System.Windows=False,System.Windows.Forms=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,iPropertiesController=True</ImportedNamespaces>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
</Project>